services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sshupdaterdb
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:8.12
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: email
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    depends_on:
      - db

  app:
    build: .
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://user:password@db:5432/sshupdaterdb
      NODE_ENV: production
      PORT: "8080"
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - /app/node_modules

volumes:
  dbdata:
